### ISSUE TITLE
~/tmp folder deleted

### ISSUE THREAD

**Issue by floesche** [e-werkzeug/easytranscript#1]
after starting easytranscript (current version 2.50 from the website) the folder `${HOME}/tmp` was deleted. Also I was not able to recover it since it seemed to have been replaced by a file in the meantime.

The deletion seems to happen in `Core/Easytranscript.java:3370` but since it says something about deleting the "tmp Update Ordner" the problem might be somewhere else (in the updater?). Please make sure not to delete any previously existing files in the home directory.

**Comment by e-werkzeug** [comment]
You are totally right. easytranscript shouldn't delete files which were created before. I fixed the easytranscript file as well as the updater. Version 2.50.1 is planned to be released on Monday (although it will be a major update, which means that easytranscript will direct you to the homepage and download the setup in order to update easytranscript, since the updater was broken in 2.50). If you want you can also download the source code and build it yourself (Updater & easytranscript). Please notice that we moved from github to bitbucket (https://bitbucket.org/ewerkzeug/).
